### PR TITLE
added CMakeLists.txt to use with cmake

### PR DESCRIPTION
**Pull request by ferkulat**
- generate project files for various IDEs

### CODE REVIEW

**Comment by ferkulat** [comment]
I forgot to set version info in CMakeLists.txt.
I am going to open a new PR

**Comment by jay** [comment]
For future reference if you add commits to the branch associated with a PR and push them then they are visible in the PR. And if you need to change the commits you can force push (`git push -f`). Also, it's easier to work from a topic branch (eg `git fetch upstream; git checkout -b topic upstream/master`) rather than master itself.

**Comment by ferkulat** [comment]
@jay Thank you for this info.
About the topic branches. Do you mean:
I can create a topic branch in my forked repo and then make a pull request for it?
And the upstream repo owner can  merge this into its master or any other branch?

Thank you in advance

**Comment by jay** [comment]
Make a branch in your local repo, work on it, then push it to your forked repo on github. When you go to your forked repo page it should detect the branch you just created and it will have a notice saying that you just created a branch with a green button create pull request. 

clipboard01

If not then you can [select the branch manually](https://help.github.com/articles/creating-a-pull-request/).

If you need to make changes to the pr then you just make them on your local branch and push that branch to github, and since the branch is associated with the pr that will update the pr as well. In many cases if nobody else is working on your work it's easier and cleaner just to force-push rather than add more commits to the branch. For example you forgot to add version info, you could add that info, amend the commit, then force push the amended commit. That change will then show in the pr without a trivial commit just for adding the version info.

**Pull request closed without merging**
