### PR TITLE
Some changes to csv.h and libcsv.c

### PR DESCRIPTION
**Pull request by bobhairgrove**
I left the version numbers alone. For anything else, such as adding the "csv_build_version()" functions I already wrote you about, we would need to up the version since it would change the interface.

### CODE REVIEW

**Review by rgamble — COMMENTED** [review]
Everything looks good, especially the corrections to broken null checks in csv_init and csv_fini.  The other functions are not intended to accept null parser objects though so I'm not sure that returning arbitrary values is better than crashing when the client misuses the interface.  Is there a compelling reason to perform these checks?

**Comment by bobhairgrove** [comment]
Hi Rob, thanks for your comments. I believe that, as a matter of principle, any function which takes a pointer as an argument should check it for NULL. As to returning arbitrary values, there could be an appropriate error code returned.

The main problem with "crashing" is that it might not crash -- it's really "undefined behavior", which includes the case that it might not crash -- until you ship the product, that is. ;)

**Comment by rgamble** [comment]
Passing null to the other functions always represents a bug on the client side.  If we want to help the user diagnose such issues, it would be better to just use assertions and I would be fine with that.

**Comment by bobhairgrove** [comment]
OK, it's really up to you ... what should I do now?

**Comment by rgamble** [comment]
Add a commit to remove the new null checks or convert them to asserts, either way is fine with me.

**Comment by bobhairgrove** [comment]
Could you be more specific as to which checks I should convert to assert ... is it just the ones for arguments of type `[const] csv_parser*`, or others as well?

**Comment by rgamble** [comment]
The new checks for null `csv_parser` pointers in `csv_error`, `csv_get_delim`, `csv_get_quote`, and `csv_parse`.  The intention is to assert when client code calls functions API functions incorrectly (meaning the client code is buggy).

**Comment by rgamble** [comment]
Need to add `#include <assert>` in libcsv.c.

**Comment by bobhairgrove** [comment]
Thanks for merging!

**Pull request merged**
